"""empty message

Revision ID: e200ddafba74
Revises: 
Create Date: 2023-06-28 05:24:02.353994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e200ddafba74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('mood')
        batch_op.drop_column('age')
        batch_op.drop_column('height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
